apiVersion: v1
kind: ResourceQuota
metadata:
  name: learning-object-limits
  namespace: k8s-learning-basics
spec:
  hard:
    pods: "200"
    count/configmaps: "20"
    count/secrets: "20"
    count/services: "10"
    count/deployments.apps: "10"
    count/daemonsets.apps: "5"
    count/statefulsets.apps: "5"
    count/jobs.batch: "20"
    count/cronjobs.batch: "10"
    persistentvolumeclaims: "10"
    requests.storage: 5Gi
