apiVersion: v1
kind: Service
metadata: 
  name: jenkins-service
  namespace: jenkins
  labels:
    app: jenkins
spec:
  type: LoadBalancer
  selector:
    app: jenkins
  ports:
      - protocol: TCP
        port: 80
        targetPort: 80


